In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [88]:
## Lets create synthetic data points
from sklearn.datasets import make_classification

In [89]:
# no. of cluster per class is 2
X,y=make_classification(n_samples=1000, n_features=2, n_classes=2, n_clusters_per_class=2, n_redundant=0, random_state=42)

In [90]:
X

array([[-0.99910178, -0.66386   ],
       [ 1.24668618,  1.15359685],
       [ 0.96277683,  0.85939747],
       ...,
       [-0.10126746, -1.59017563],
       [ 0.64376105, -0.78053855],
       [ 0.69852984, -1.27940455]])

In [91]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,

In [92]:
pd.DataFrame(X)[0]

0     -0.999102
1      1.246686
2      0.962777
3     -2.957441
4      1.141165
         ...   
995   -0.432774
996    1.020438
997   -0.101267
998    0.643761
999    0.698530
Name: 0, Length: 1000, dtype: float64

In [93]:
sns.scatterplot(x=pd.DataFrame(X)[0],y=pd.DataFrame(X)[1],hue=y)

<Axes: xlabel='0', ylabel='1'>

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=42)

In [95]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [116]:
from sklearn.svm import SVC
# for this type of data points use rbf kernal 
rbf = SVC(kernel='rbf', gamma='scale')

In [117]:
# train the model using rbg kernel 
rbf.fit(X_train, y_train)

SVC()

In [ ]:
##Prediction
y_pred1 = rbf.predict(X_test)

In [98]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(classification_report(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1)) 
# we got 89 percent accuracy using rbf kernel  

              precision    recall  f1-score   support

           0       0.85      0.93      0.89       121
           1       0.93      0.84      0.89       129

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250

[[113   8]
 [ 20 109]]


In [100]:
rbf.intercept_

array([0.43183122])

In [ ]:
# now train the model using polynomial kernel 
polynomial = SVC(kernel='poly', degree=3)
polynomial.fit(X_train, y_train)

SVC(kernel='poly')

In [ ]:
# Prediction
y_pred2 = polynomial.predict(X_test)

In [ ]:
print(classification_report(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2)) 
# we got 88% accuracy using polynomial kernel 

              precision    recall  f1-score   support

           0       0.89      0.85      0.87       121
           1       0.87      0.90      0.88       129

    accuracy                           0.88       250
   macro avg       0.88      0.88      0.88       250
weighted avg       0.88      0.88      0.88       250

[[103  18]
 [ 13 116]]


In [104]:
polynomial.intercept_

array([0.03120858])

In [ ]:
# now train the model using polynomial kernel 
sigmoid = SVC(kernel='sigmoid')
sigmoid.fit(X_train,y_train)


SVC(kernel='sigmoid')

In [ ]:
# Prediction
y_pred3=sigmoid.predict(X_test)

In [ ]:
print(classification_report(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3)) 
# we got 74% accuracy using sigmoid kernel 

              precision    recall  f1-score   support

           0       0.75      0.70      0.72       121
           1       0.74      0.78      0.75       129

    accuracy                           0.74       250
   macro avg       0.74      0.74      0.74       250
weighted avg       0.74      0.74      0.74       250

[[ 85  36]
 [ 29 100]]


In [119]:
sigmoid.intercept_

array([-0.43859428])

## Hyperparameter tunnig with SVC using GridsearchCV

In [121]:
from sklearn.model_selection import GridSearchCV

In [123]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

In [129]:
grid=GridSearchCV(SVC(), param_grid=param_grid, refit=True, cv=5, verbose=3)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.927 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.860 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.893 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.860 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.853 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.900 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.840 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.867 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.880 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.827 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.867 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [125]:
print(grid.best_params_)

{'C': 1000, 'gamma': 1, 'kernel': 'rbf'}


In [130]:
rbf = SVC(kernel='rbf',gamma='scale')
rbf.fit(X_train, y_train)

SVC()

In [135]:
y_pred4=grid.predict(X_test)
print(classification_report(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))
# we got 92% accuracy by doing hyperparameter tunnig 

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       121
           1       0.97      0.86      0.91       129

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250

[[118   3]
 [ 18 111]]
